name: Build openreads-to-storygraph

on: push

jobs:
  package_source:
    name: Package Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-mark manual ghc # Don't bother installing ghc just to tar up source
          sudo apt-get install cabal-install

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deduce tags
        run: |
          mkdir source
          echo "latest" > source/tags
          if tag=$(git describe --exact-match --tags)
          then
            echo "stable" >> source/tags
            echo "$tag" >> source/tags
          fi
          cat source/tags

      - name: Package Source
        run: |
          grep "stable" source/tags || ./setgitversion
          cabal sdist
          mv dist-newstyle/sdist/*.tar.gz source/source.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: source/
  build_source:
    name: Build
    needs: package_source
    strategy:
      matrix:
        build: [linux.x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Build source
        run: |
          mkdir -p bin
          mkdir -p bin/${{matrix.build}}
          ( cd bin && ../build/run_builder ../source/source.tar.gz ../build/${{matrix.build}} )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.build}}.bin
          path: bin/
  package_binary:
    name: Package Binaries
    needs: build_source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Work around GitHub permissions bug
        run: chmod +x *.bin/*/universum-diary-tools-exe*

      - name: Package binaries
        run: |
          export TAGS="$(cat source/tags)"
          mkdir -p deploy
          cp -r *.bin/* deploy
          cd deploy
          ../.prepare_deploy
          rm -rf */ README* LICENSE*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy/
